#Extra Credit For Lab 2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

 
```{r Data, include = FALSE}
library(sf)
library(tmap)
WAC <- read.csv("wa_wac_S000_JT00_2015.csv")
tacomablockshp <- st_read("tacomablocks-polygon.shp")
```

```{r Merging, include = FALSE}
library(dplyr)

Columns <- select(WAC, w_geocode, CNS05, CNS06, CNS16, CD01, CD04)

Columns$w_geocode[which(length(Columns$w_geocode) == 14)]<-paste0("0", Columns$w_geocode[which(length(Columns$w_geocode) == 4)])

Columns$GEOID10 =Columns$w_geocode  

WACBLOCK <- merge(tacomablockshp, Columns, by=c("GEOID10"))
```

#Static choropleth maps 
```{r Static Maps, include = TRUE}
#Static choropleth maps 
tm_shape(WACBLOCK) +tm_fill(col="CNS05", title = "Number of Jobs") + tm_borders() + tm_layout(title = "All manufacturing jobs in Tacoma ", title.position = c("RIGHT", "TOP")) 

tm_shape(WACBLOCK) +tm_fill(col="CNS06", title = "Number of Jobs") + tm_borders() +tm_layout(title = "All Transportation and Warehousing jobs in Tacoma", title.position = c("RIGHT", "TOP")) 

tm_shape(WACBLOCK) +tm_fill(col="CNS16", title = "Number of Jobs") + tm_borders() +tm_layout(title = "All Health Care and Social Assistance jobs in Tacoma", title.position = c("RIGHT", "TOP")) 
```

#Interative cholopleth maps 
```{r Interactive Maps, include = TRUE}
#Interative cholopleth maps 
tmap_mode("view") + tm_shape(WACBLOCK) + tm_fill("CD01", title = "Number of Jobs") + tm_borders() + tm_layout(title = "All jobs for workers with Educational Attainment: Bachelor’s Degree or advanced degree", title.position = c("RIGHT", "TOP")) 

tmap_mode("view") + tm_shape(WACBLOCK) + tm_fill("CD04", title = "Number of Jobs") +tm_borders() + tm_layout(title = "All jobs for workers with Educational Attainment: Less than high school in Tacoma", title.position = c("RIGHT", "TOP")) 
```

